
#include "command.h"

void
command_set_token_init (command_set_token_t *command, unsigned int token)
{
    command->token = token;
}

size_t
command_get_size (command_type_t command_type)
{
    if (command_type == COMMAND_NO_OP)
        return 0;
    if (command_type == COMMAND_SET_TOKEN)
        return sizeof (command_set_token_t);
    if (command_type == COMMAND_GLMULTIDRAWELEMENTSEXT)
        return 0; /* FIXME: Not implemented. */
    if (command_type == COMMAND_EGLTERMINATE)
        return 0; /* FIXME: Not implemented. */
    if (command_type == COMMAND_EGLMAKECURRENT)
        return 0; /* FIXME: Not implemented. */
    if (command_type == COMMAND_EGLSWAPBUFFERS)
        return 0; /* FIXME: Not implemented. */
    if (command_type == COMMAND_GLDRAWARRAYS)
        return 0; /* FIXME: Not implemented. */
    if (command_type == COMMAND_GLDRAWELEMENTS)
        return 0; /* FIXME: Not implemented. */
    if (command_type == COMMAND_GLPIXELSTOREI)
        return 0; /* FIXME: Not implemented. */

    return command_get_size_autogenerated (command_type);
}
