
#include "command.h"

void
command_set_token_init (command_set_token_t *command, unsigned int token)
{
    command->token = token;
}

size_t
command_get_size (command_id_t command_id)
{
    if (command_id == COMMAND_NO_OP)
        return 0;
    if (command_id == COMMAND_SET_TOKEN)
        return sizeof (command_set_token_t);
    if (command_id == COMMAND_GLCREATESHADER)
        return sizeof (command_glcreateshader_t);
    if (command_id == COMMAND_GLGETSTRING)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_GLGETVERTEXATTRIBPOINTERV)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_GLSHADERSOURCE)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_GLGETBUFFERPOINTERVOES)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_GLMULTIDRAWELEMENTSEXT)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_GLEXTGETBUFFERPOINTERVQCOM)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_EGLGETERROR)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_EGLTERMINATE)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_EGLQUERYSTRING)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_EGLMAKECURRENT)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_EGLSWAPBUFFERS)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_EGLGETPROCADDRESS)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_EGLCLIENTWAITSYNCKHR)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_EGLCLIENTWAITSYNCNV)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_EGLQUERYSURFACEPOINTERANGLE)
        return 0; /* FIXME: Not implemented. */
    if (command_id == COMMAND_EGLMAPIMAGESEC)
        return 0; /* FIXME: Not implemented. */

    return command_get_size_autogenerated (command_id);
}
