
#include <gpuprocess_command.h>

void
command_set_token_init (command_set_token_t *command, unsigned int token)
{
    command->token = token;
}

size_t
command_get_size (command_id_t command_id)
{
    if (command_id == COMMAND_NO_OP)
        return 0;
    if (command_id == COMMAND_SET_TOKEN)
        return sizeof (command_set_token_t);
    return command_get_size_autogenerated (command_id);
}
